### ISSUE TITLE
Does not work with Ipad/Iphone

### ISSUE THREAD

**Issue by lfjeff** [codedance/jquery.AreYouSure#34]
Has anyone figured out how to make this work with Ipad/Iphone browsers?

They do not handle the 'beforeunload' event properly and I've been beating my head trying to figure out how to issue a message if anything in the form changes.  I tried your module and used 'pagehide' instead of 'beforeunload', but it did not work.

**Comment by highdownts** [comment]
My usage requirement is slightly different. I would like to save data to isolated storage on before unload. I am going to have a look at the code, but wanted to see if you thought this was possible with your code base. 

Thanks...
