### ISSUE TITLE
input[type=hidden] is not being checked for dirty

### ISSUE THREAD

**Issue by SachinPuthran** [codedance/jquery.AreYouSure#38]
The input[type=hidden] is not getting checked for dirty because neither the change or keyup events are getting fired on change of the value. 

Work around that i am using is to trigger the keyup event when the change is done to the input[type=hidden] value. 

Thank you for this great and easy plugin!

**Comment by taberrr** [comment]
@codedance @SachinPuthran unless it's something specific to my environment or a different version of jQuery or something (using 2.2.4) neither of these fixes seem to work any more :(
