### ISSUE TITLE
Checking which button was clicked...

### ISSUE THREAD

**Issue by davidangel** [codedance/jquery.AreYouSure#6]
Is there a way to test the the result of the AYS result in a function that is fired later? I want to test the value in an onclick function, and do different things based on what the user clicked. Any ideas?

**Comment by SMohanraj** [comment]
I want to bind a custom function on click of "Leave this page" or "stay on the page" . 
My main purpose to bind Asp.net control or html control.

Thanks.

**Comment by codedance** [comment]
@SMohanraj This is possible as part of the standard "beforeunload" page event.  Are-You-Sure will not change or affect your own handler.  

https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload

Hope this helps.
