### ISSUE TITLE
Override the OnBeforeUnload dialog and replace it with my own

### ISSUE THREAD

**Issue by aleczandra** [codedance/jquery.AreYouSure#64]
Is it possible to override the onbeforeunload dialog and replace it with a custom confirmation dialog?
This would be a nice feature. I tried to use the plugin, it works fine, but I need to show our own confirmation dialog.

**Comment by shubhamkundu** [comment]
Hi All,

Is the only answer still relevant for modern day browsers?
Any help is appreciated

**Comment by cristianab** [comment]
Starting with Firefox 44, Chrome 51, Opera 38 and Safari 9.1, a generic string not under the control of the webpage will be shown instead of the returned string.
