### ISSUE TITLE
Safari Mobile - how to display prompt message and prevent refreshing page without clicking any links

### ISSUE THREAD

**Issue by saigitaccount** [codedance/jquery.AreYouSure#70]
I'm trying to show the prompt message and prevent refreshing page if user's trying to refresh the page.

I would like the message can be shown if user hasn't click on any links yet, just refresh the page.

So I made something similar to ays-beforeunload-shim.js like this:

var iOS = ( navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false );
if(iOS){

	window.onunload = function() {				
	 var response = $(window).triggerHandler('beforeunload', response);
	if (response && response != "") {
		var msg = response + "\n\n"
		  + "Press OK to leave this page or Cancel to stay!!!.";
		if (!confirm(msg)) {
		  return false;
		}
	  }
	}
}

I can see the message but cannot prevent reloading page even I clicked "Cancel" on the prompt.

Is there anyway to make this done?

**Comment by codedance** [comment]
Closing off this old issue.  It should be addressed with the project's shim.
